### PR TITLE
Resolve multiple bugs

### LINKED ISSUE #71: Use of reserved keywords if present in route name
### Wayfinder Version

0.1.6

### Laravel Version

12.15.0

### PHP Version

8.4

### Description

If a reserved keyword (like "default") is being used inside a route name (for example "default.login") the generated exports for the route will look similar to this:

```ts
const default = {
    login,
}

export default default
```

### Steps To Reproduce

Add reserved keyword to any route name, run `php artisan wayfinder:generate` and inspect the related files

### PR DESCRIPTION
**Pull request by istiak-tridip**
This PR fixes a few bugs & makes some refactors.

### Bugs Fixed

1. Handle route names that start with characters invalid for JavaScript identifiers
```php
// Example
Route::get('/auth/2fa', TwoFactorAuthChallenge::class)->name('2fa.challenge');
```
2. Handle invalid JS identifiers and reserved keywords in barrel file exports (fixes #71)
```php
// Example
Route::get('/login', DefaultLogin::class)->name('default.login');
```

4. Expanded the list of reserved JavaScript/TypeScript keywords to fix naming conflicts
```php
// Example
Route::get('/protected/blog-post', TwoFactorAuthChallenge::class)->name('protected.post');
```
5. Fixed JSDoc `@see` tags for invokable controller routes
```php
// Example route
Route::get('/', HomePage::class)->name('home');
```

```diff
- * @see \App\Domains\Public\Pages\HomePage::home
+ * @see \App\Domains\Public\Pages\HomePage::__invoke
```

### Refactors
- Replaced the `md5` hashing algorithm with the significantly faster `xxh3`
- Refactored the conditions determining when generated route helpers are `export`ed, as part of fixing the JSDoc issue for invokable routes.

---
P.S. Hey @joetannenbaum, a quick question regarding reserved route names like `delete` becoming `deleteMethod`. Given these are routes, I wondered if `Route` (e.g., `deleteRoute`) might be an alternative. Appreciate any insight!

### CODE REVIEW

File: src/TypeScript.php [hunk 1]
```diff
@@ -42,6 +42,17 @@ class TypeScript
         'void',
         'while',
         'with',
+        'public',
```
Comment (SuperDJ) [inline src/TypeScript.php:45]: Like the others, please add in alphabetical order

**Comment by joetannenbaum** [comment]
Thanks! Good point on naming, I'll re-examine in the next Wayfinder beta coming up 👍
